### ISSUE TITLE
Funções de operação em interface

### ISSUE THREAD

**Issue by laisbastosbg** [JoanWilson/Setterfolder#1]
Acredito que as seguintes funções deveriam estar no arquivo operations, pois não dizem respeito a interface e sim, as operações que o programa realiza

https://github.com/JoanWilson/Setterfolder/blob/50600e28c6ceb1e922d1788fff4a3a9822f2746b/Sources/Setterfolder/Interface.swift#L60-L96

**Comment by JoanWilson** [comment]
Pois é elas estavam lá mas eu acabei tirando, pois pensei que diziam a respeito somente a opção do usuário, mas vendo agora, percebi que você tem total razão. Muito obrigado Lais!
