### ISSUE TITLE
UX Suggestion

### ISSUE THREAD

**Issue by joaoipiraja** [JoanWilson/Setterfolder#3]
Here's some suggestions for your project distribution 

- [ ] Generate a unix executable file of your project 

💡Example:
`Xcode > Product > Archive > Distribute Content > Build Products `

- [ ] Upload the executable file to GitHub as a release 

[📖 Read more](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)

- [ ] Add a Mac installation guide to your readme

💡Example:
```terminal

cd /usr/local/bin
sudo curl -OL https://github.com/YOURUSER/YOUR REPO/releases/latest/download/EXECUTABLE FILE WITHOUT .EXE
sudo chmod 755 EXECUTABLE FILE WITHOUT .EXE

```

**Comment by JoanWilson** [comment]
Thanks a lot João. I'm working on it in order to make my project distribution better.
