### ISSUE TITLE
Comentário do Programa✨

### ISSUE THREAD

**Issue by SarahMadalena** [JoanWilson/Setterfolder#4]
Eu gostei muito da ideia do programa, também gostei muito dos comentários no código, pois me fez entender melhor o que estava acontecendo . Gostaria de entender sobre Manipulação de Path 🥳.

**Comment by JoanWilson** [comment]
Muito obrigado Sarah! Aquela maneira estava dando um erro, mas eu consegui obter o path do usuário, utilizando um comando bash dentro do programa, ou seja, um pwd.
