### ISSUE TITLE
Quando vou organizar a pasta Downloads, é repassado esse erro, sugiro revisão da pasta do usuário

### ISSUE THREAD

**Issue by kipras-pal** [JoanWilson/Setterfolder#5]
https://github.com/JoanWilson/Setterfolder/blob/382ca28dd80f70e7c88c876c0bdd06ba4d0203eb/Sources/Setterfolder/Interface.swift#L93

**Comment by JoanWilson** [comment]
Oi Christian, o erro foi resolvido, pode dar clone na nova versão
